name: Copy index.html to 404.html

on:
  push:
    branches:
      - master

jobs:
  copy_index_to_404:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout

      - name: Copy index.html to 404.html
        run: cp docs/index.html docs/404.html

      - name: Commit and push 404.html
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add 404.html
          git commit -m "Add 404.html copied from index.html"
          git push
